import React, { useState } from 'react';
import AppLayout from '@/layouts/app-layout';
import { Head, useForm, router } from '@inertiajs/react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useFlashToast } from '@/hooks/useFlashToast';
import type { BreadcrumbItem } from '@/types';

interface Settings {
    global_start_number: number;
    current_next_number: number;
    total_issued: number;
}

interface IndexProps {
    settings: Settings;
}

const breadcrumbs: BreadcrumbItem[] = [
    { title: 'Dashboard', href: route('dashboard') },
    { title: 'Certificate Settings', href: route('admin.certificate-settings.index') },
];

export default function Index({ settings }: IndexProps) {
    useFlashToast();

    const [masterTemplateFile, setMasterTemplateFile] = useState<File | null>(null);
    const [isDownloading, setIsDownloading] = useState(false);
    const [isUploading, setIsUploading] = useState(false);

    const { data, setData, patch, processing, errors } = useForm({
        global_start_number: settings.global_start_number
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        patch(route('admin.certificate-settings.update'));
    };

    const handleDownloadTemplate = () => {
        setIsDownloading(true);
        window.location.href = route('admin.certificate-template.download');
        setTimeout(() => setIsDownloading(false), 2000);
    };

    const handleUploadMasterTemplate = () => {
        if (!masterTemplateFile) return;

        setIsUploading(true);
        router.post(route('admin.certificate-template.upload-master'), {
            master_template: masterTemplateFile
        }, {
            onFinish: () => {
                setIsUploading(false);
                setMasterTemplateFile(null);
            }
        });
    };

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title="Certificate Settings" />

            <div className="m-4 space-y-6">
                {/* Certificate Statistics */}

                {/* Global Settings */}
                <Card>
                    <CardHeader>
                        <CardTitle>Global Certificate Settings</CardTitle>
                    </CardHeader>
                    <CardContent>
                        <form onSubmit={handleSubmit} className="space-y-4">
                            <div>
                                <Label htmlFor="global_start_number">
                                    Global Starting Number
                                </Label>
                                <Input
                                    id="global_start_number"
                                    type="number"
                                    min="1"
                                    value={data.global_start_number}
                                    onChange={(e) => setData('global_start_number', parseInt(e.target.value))}
                                    className="w-40"
                                />
                                <p className="text-sm text-muted-foreground mt-1">
                                    If your last manual certificate was #103, set this to 104
                                </p>
                                {errors.global_start_number && (
                                    <p className="text-sm text-red-500 mt-1">{errors.global_start_number}</p>
                                )}
                            </div>

                            <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                                <h4 className="font-medium text-yellow-800">Example:</h4>
                                <p className="text-sm text-yellow-700 mt-1">
                                    If you have issued 150 certificates manually, set the Global Starting Number to 151. The next certificate generated by the system will be #151, and subsequent certificates will increment from there.
                                </p>
                            </div>

                            <Button type="submit" disabled={processing}>
                                {processing ? 'Updating...' : 'Update Settings'}
                            </Button>
                        </form>
                    </CardContent>
                </Card>

                {/* Template Management */}
                <Card>
                    <CardHeader>
                        <CardTitle>Master Certificate Template</CardTitle>
                        <p className="text-sm text-muted-foreground">
                            Manage the master template that admins will download and customize for events
                        </p>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        {/* Upload Master Template */}
                        <div>
                            <h4 className="font-medium mb-3">Upload Master Template</h4>
                            <div className="flex items-center gap-3">
                                <Input
                                    type="file"
                                    accept=".docx"
                                    onChange={(e) => setMasterTemplateFile(e.target.files?.[0] || null)}
                                    className="w-64"
                                />
                                <Button
                                    onClick={handleUploadMasterTemplate}
                                    disabled={!masterTemplateFile || isUploading}
                                    variant="outline"
                                >
                                    {isUploading ? 'Uploading...' : 'Upload'}
                                </Button>
                            </div>
                            <p className="text-xs text-muted-foreground mt-1">
                                Upload the master DOCX template with parameters like {'{participant_name}'}, {'{event_name}'}, etc.
                            </p>
                        </div>

                        <div className="border-t pt-6">
                            <h4 className="font-medium mb-3">Download Master Template</h4>
                            <div className="flex items-center gap-3">
                                <Button
                                    onClick={handleDownloadTemplate}
                                    disabled={isDownloading}
                                    variant="outline"
                                >
                                    {isDownloading ? 'Downloading...' : '📄 Download Master Template'}
                                </Button>
                                <span className="text-sm text-muted-foreground">
                                    Admins can download this template to customize for their events
                                </span>
                            </div>
                        </div>

                        {/* Instructions */}
                        <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                            <h4 className="font-medium text-blue-800 mb-2">How it works:</h4>
                            <div className="text-sm text-blue-700 space-y-1">
                                <p>1. <strong>You upload</strong> a master DOCX template with parameters</p>
                                <p>2. <strong>Admins download</strong> the master template when creating events</p>
                                <p>3. <strong>Admins customize</strong> the template (add backgrounds, logos, etc.)</p>
                                <p>4. <strong>Admins upload</strong> their customized version for specific events</p>
                                <p>5. <strong>System generates</strong> certificates using their custom design</p>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
